import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { AspectRatio, Media, Video } from "@vidstack/player/react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vidstack autoplay bug in Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Vidstack Video Player</h1>

        <div className={styles.video}>
          <Media>
            <AspectRatio ratio="16/9" minHeight="150px" maxHeight="1000px">
              <Video
                poster="https://media-files.vidstack.io/poster.png"
                autoplay
                loop
              >
                <video
                  src="https://media-files.vidstack.io/720p.mp4"
                  poster="https://media-files.vidstack.io/poster-seo.png"
                  preload="none"
                ></video>
              </Video>
            </AspectRatio>
          </Media>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
